maxPlayers: 12
worldFolderPath: "/home/tokyo/Tokyo-Build/BauserverMaptests/Wrapper/local/templates/OITC/Maps"
#In seconds
timeToStart: 60
forceTime: 10
protectionTime: 3
#In minutes
gameDuration: 5
lobbySpawn: