maxPlayers: 12
mapWorldFolder: "/home/tokyo/Tokyo-Build/BauserverMaptests/Wrapper/local/templates/OITC/Maps"
mapConfigFolder: "/home/tokyo/Tokyo-Build/BauserverMaptests/Wrapper/local/templates/OITC/default/plugins/OneInTheChamber/maps"
#In seconds
timeToStart: 60
forceTime: 10
protectionTime: 3
#In minutes
gameDuration: 5
ffaGameDuration: 60
lobbySpawn: